version: "3"

services:
    swrm-php:
        image: sunbaby/php
        deploy:
          replicas: 2
        ports:
            - 8080:80
        volumes:
            - "/home/ubuntu/php:/var/www/html:ro"
        networks:
            - swrm-network
        depends_on:
            - swrm-mysql

    swrm-mysql:
        image: sunbaby/mysql
        networks:
            - swrm-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"

networks:
    swrm-network:
