---
  - name: Remove existing copy of dob-network on docker host ...
    command: bash -c "docker network rm dob-network 1 > /dev/null 2>&1 || true"
  - name: Add dob-network to docker host ...
    command: docker network create --driver bridge dob-network 
  - name: Copy docker directory to remote server
    copy:
      src: docker/
      dest: /home/ubuntu/docker
  - name: Copy php directory to remote server
    copy:
      src: php/
      dest: /home/ubuntu/php
  - name: Create swarm 
    command: docker swarm init
  - name: Deploy the docker stack 
    command: docker stack deploy -c docker/docker-compose.yml docker-help 
